# Generated by Django 4.2.7 on 2023-11-19 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='number',
            field=models.BigIntegerField(unique=True),
        ),
    ]
