# Generated by Django 4.2.7 on 2023-11-20 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0004_remove_merchant_private_key_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='business_hours',
            field=models.JSONField(),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='category',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='merchant',
            name='payment_methods_accepted',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('CREDIT_CARD', 'Credit Card')], max_length=20),
        ),
    ]
