# Generated by Django 4.2.7 on 2023-11-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merchants', '0006_alter_merchant_api_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='user',
        ),
    ]
