# Generated by Django 4.2.7 on 2023-11-22 13:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_created_date'),
        ('merchants', '0007_remove_merchant_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='merchant',
            name='account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='accounts.account'),
        ),
    ]
