# Generated by Django 4.2.7 on 2023-12-19 13:15

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_number', models.BigIntegerField()),
                ('transaction_type', models.CharField(choices=[('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('DEBIT_CARD', 'Debit Card'), ('PAYMENT', 'Payment')], default='DEPOSIT', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('identifier', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='accounts.account')),
            ],
        ),
    ]
