# Generated by Django 4.2.7 on 2023-11-27 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('USER_NOTIFICATION', 'User Notification'), ('TRANSACTION_ALERT', 'Transaction Alert'), ('ACCOUNT_ALERT', 'Account Alert'), ('SECURITY_NOTIFICATION', 'Security Notification')], max_length=30),
        ),
    ]
