# Generated by Django 4.2.7 on 2023-11-23 03:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debitcard',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 11, 22, 3, 16, 40, 234072)),
        ),
    ]
