# Generated by Django 4.2.7 on 2023-11-22 22:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='due_date',
        ),
    ]
