# Generated by Django 4.2.7 on 2023-11-21 18:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 11, 20, 18, 22, 27, 544131)),
        ),
    ]
