# Generated by Django 4.2.7 on 2023-11-22 13:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_cards', '0004_alter_creditcard_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='expiration_date',
            field=models.DateTimeField(default=datetime.datetime(2026, 11, 21, 13, 44, 55, 374057)),
        ),
    ]
