# Generated by Django 4.2.7 on 2023-11-22 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_rename_type_transaction_transaction_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('PAYMENT', 'Payment')], default='DEPOSIT', max_length=20),
        ),
    ]
