# Generated by Django 4.2.7 on 2023-11-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_alter_transaction_transaction_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='account',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.BigIntegerField(default=123456789011123, unique=True),
            preserve_default=False,
        ),
    ]
