# Generated by Django 4.2.7 on 2023-11-23 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_alter_transaction_account_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('DEPOSIT', 'Deposit'), ('TRANSFER', 'Transfer'), ('DEBIT_CARD', 'Debit Card'), ('PAYMENT', 'Payment')], default='DEPOSIT', max_length=20),
        ),
    ]
