# Generated by Django 4.2.7 on 2023-12-18 22:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
    ]
