name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - uses: ikalnytskyi/action-setup-postgres@v4
      with:
        username: postgres
        password: fakepassword001
        database: virtual_bank
        port: 5432
      id: postgres

    - run: pytest -vv tests/
      env:
        CONNECTION_STR: ${{ steps.postgres.outputs.connection-uri }}
  
    - run: pytest -vv tests/
      env:
        CONNECTION_STR: service=${{ steps.postgres.outputs.service-name }}
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run Tests
      run: |
        python ./backend/manage.py test
